export enum ChannelsEnum {
  whatsapp = 'whatsapp',
  telegram = 'telegram',
  instagram = 'instagram',
  slack = 'slack',
  discord = 'discord',
  teams = 'teams',
  email = 'email',
  sms = 'sms',
  pushNotification = 'pushNotification',
  facebookMessenger = 'facebookMessenger',
  twitter = 'twitter',
  linkedin = 'linkedin',
  voiceCall = 'voiceCall',
  videoCall = 'videoCall',
  inAppNotification = 'inAppNotification',
}